apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gcsweb-ing
  namespace: gcs
  annotations:
    kubernetes.io/ingress.global-static-ip-name: gcs
    networking.gke.io/managed-certificates: gcs-istio-io
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
  - host: gcsweb.istio.io
    http:
      paths:
      - path: /*
        backend:
          serviceName: gcsweb
          servicePort: 80
